const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// uploads lives at backend/uploads/ (two levels up from backend/src/services/)
const UPLOADS_DIR = path.join(__dirname, '../../uploads');

// ---------------------------------------------------------------------------
// Markdown parser — handles the structured output produced by the LLM
// Supported tokens:
//   **text**         → bold heading-style line
//   * text           → bullet point
//   plain text       → normal paragraph
// ---------------------------------------------------------------------------
function parseMarkdown(text) {
  const tokens = [];
  const lines = text.split('\n');

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      tokens.push({ type: 'spacer' });
      continue;
    }
    // Bold heading: **text** alone on a line
    if (/^\*\*(.+)\*\*$/.test(line)) {
      tokens.push({ type: 'heading', text: line.replace(/\*\*/g, '') });
    }
    // Bullet: * text  or - text
    else if (/^[*-]\s+(.+)/.test(line)) {
      tokens.push({ type: 'bullet', text: line.replace(/^[*-]\s+/, '') });
    }
    // Inline bold: strip ** markers, keep text
    else {
      tokens.push({ type: 'paragraph', text: line.replace(/\*\*/g, '') });
    }
  }
  return tokens;
}

// ---------------------------------------------------------------------------
// PDF builder helpers
// ---------------------------------------------------------------------------

function addHeader(doc, title) {
  doc.font('Helvetica-Bold')
     .fontSize(22)
     .fillColor('#4F46E5')
     .text('EduFlow LMS', 50, 50);

  doc.font('Helvetica')
     .fontSize(10)
     .fillColor('#6B7280')
     .text('AI-Generated Course Summary', 50, 78);

  doc.moveDown(1.5)
     .font('Helvetica-Bold')
     .fontSize(16)
     .fillColor('#111827')
     .text(title, { align: 'center' });

  // Divider
  const y = doc.y + 10;
  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, y).lineTo(545, y).stroke();
  doc.moveDown(1.5);
}

function addCourseInfo(doc, courseData) {
  doc.font('Helvetica')
     .fontSize(10)
     .fillColor('#6B7280');

  const fields = [
    ['Module', courseData.moduleName || 'N/A'],
    ['Video', courseData.videoUrl || 'N/A'],
    ['Generated', new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
  ];

  fields.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').text(`${label}: `, { continued: true })
       .font('Helvetica').text(value);
  });

  doc.moveDown(1);
  const y = doc.y;
  doc.strokeColor('#E5E7EB').lineWidth(0.5).moveTo(50, y).lineTo(545, y).stroke();
  doc.moveDown(1.5);
}

function addSummaryContent(doc, summaryText) {
  const tokens = parseMarkdown(summaryText);

  for (const token of tokens) {
    switch (token.type) {
      case 'heading':
        doc.moveDown(0.5)
           .font('Helvetica-Bold')
           .fontSize(13)
           .fillColor('#1E40AF')
           .text(token.text);
        doc.moveDown(0.3);
        break;

      case 'bullet':
        doc.font('Helvetica')
           .fontSize(11)
           .fillColor('#374151')
           .text(`•  ${token.text}`, {
             indent: 12,
             lineGap: 3,
           });
        break;

      case 'paragraph':
        doc.font('Helvetica')
           .fontSize(11)
           .fillColor('#374151')
           .text(token.text, {
             align: 'justify',
             lineGap: 4,
           });
        doc.moveDown(0.4);
        break;

      case 'spacer':
        doc.moveDown(0.3);
        break;
    }
  }
}

function addFooters(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.font('Helvetica')
       .fontSize(9)
       .fillColor('#9CA3AF')
       .text(
         `Page ${i + 1} of ${range.count}  •  Generated by EduFlow LMS`,
         50,
         doc.page.height - 45,
         { align: 'center', width: doc.page.width - 100 }
       );
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

async function generateCoursePDF(courseData) {
  return new Promise((resolve, reject) => {
    try {
      if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });

      const safeName = (courseData.title || 'course')
        .replace(/[^a-zA-Z0-9]/g, '-')
        .toLowerCase()
        .slice(0, 60);
      const timestamp = Date.now();
      const filename = `course-summary-${safeName}-${timestamp}.pdf`;
      const filePath = path.join(UPLOADS_DIR, filename);

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 60, left: 50, right: 50 },
        bufferPages: true,   // required for addFooters()
      });

      const writeStream = fs.createWriteStream(filePath);
      doc.pipe(writeStream);

      addHeader(doc, courseData.title || 'Course Summary');
      addCourseInfo(doc, courseData);
      addSummaryContent(doc, courseData.summaryText || '');

      // Add page numbers to all pages before flushing
      addFooters(doc);

      doc.end();

      writeStream.on('finish', () => resolve(`/uploads/${filename}`));
      writeStream.on('error', (err) => reject(new Error(`Write stream error: ${err.message}`)));

    } catch (err) {
      reject(new Error(`PDF generation failed: ${err.message}`));
    }
  });
}

async function deletePDF(filePath) {
  try {
    const full = path.join(__dirname, '../../', filePath);
    if (fs.existsSync(full)) fs.unlinkSync(full);
    return true;
  } catch {
    return false;
  }
}

function pdfExists(filePath) {
  try {
    return fs.existsSync(path.join(__dirname, '../../', filePath));
  } catch {
    return false;
  }
}

module.exports = { generateCoursePDF, deletePDF, pdfExists };
